version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - SECRET_KEY=your_secret_key
      - DB_HOST=your_db_host
      - DB_PORT=your_db_port
      - DB_USER=your_db_user
      - DB_PASSWORD=your_db_password
      - DB_NAME=your_db_name
  frontend:
    build: ./frontend
    ports:
      - "80:80"
